name: CI
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  release:
    types:
      - published
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run-s test:lint
  lint-example:
    name: Lint Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - working-directory: ./example
        run: npm ci
      - working-directory: ./example
        run: npm run lint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run-s test:prettier
  prettier-example:
    name: Prettier Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - working-directory: ./example
        run: npm ci
      - working-directory: ./example
        run: npm run prettier:check
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run-s test:ts
  test:
    name: Test
    runs-on: ubuntu-latest
    if: false # Disable test for now
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run-s test:unit
      - uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run-s build
      - working-directory: ./example
        run: npm install
      - working-directory: ./example
        run: npm run build
      - if: ((github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event.action == 'published')
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: example-app
          path: example/out/**
  publish:
    needs:
      - lint
      - lint-example
      - prettier
      - prettier-example
      - typescript
      # - test
      - build
    if: github.event.action == 'published'
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 20
      - run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.ORG_NPM_TOKEN }}
          access: 'public'
